### ISSUE TITLE
[Feat] 누끼 기능 개선 #2

### ISSUE THREAD

**Issue by xnoag** [DeveloperAcademy-POSTECH/MC2-Team10-BuriBuri#1]
# ✏️Description
누끼 기능 개선

# 🛠️Todo
- [ ] 테두리 없앤 PNG 이미지와 텍스처 입힌 USDZ 저장하는 함수 만들기
- [ ] 저장 버튼 눌렀을 때 저장할 수 있게 함수 2단계로 하기
- [ ] 제일 큰 덩어리 하나만 남기고 없애기
- [ ] 배경이 제대로 없어진 것 맞나? 배경 날리는 코드 재검토
- [ ] 5초는 기니까 속도 개선하기
- [ ] 함수 비동기로 하기

# ⚙️ETC
- 추가적인 설명
