### ISSUE TITLE
[Feat] AR 객체 속성

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MC2-Team10-BuriBuri#3]
# ✏️Description
AR에 생성된 객체의 속성과 관련한 기능 개발

# 🛠️Todo
- [ ] Album에 있는 것을 선택하면 AR 화면에 띄우기
- [ ] AR 객체: 클릭 -> 물성 변경
- [ ] AR 객체: 클릭해서 드래그 -> 위치 변경
- [ ] AR 객체: 클릭해서 아래 휴지통으로 드래그 -> 삭제

# ⚙️ETC
- 추가적인 설명
