### ISSUE TITLE
[Feat] AlbumView 관련

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MC2-Team10-BuriBuri#4]
# ✏️Description
AlbumView 관련 기능 개발

# 🛠️Todo
- [ ] 편집을 할 수 있는 부모용 AlbumView
- [ ] 오브젝트를 띄우기만 할 수 있는 아이용 AlbumView
- [ ] AlbumView sheet으로 띄울 때 opacity 주기

# ⚙️ETC
- 추가적인 설명
