### ISSUE TITLE
[Feat] 2D extrusion으로 3D 객체 생성하기

### ISSUE THREAD

**Issue by unboxing96** [DeveloperAcademy-POSTECH/MC2-Team10-BuriBuri#5]
# ✏️ Description
BezierPath와 SCNShape 활용해서 2D extrusion으로 3D 객체 생성하기

# 🛠️ Todo
- [ ] ext1_PEPE : BezierPath 받아서 SCNShape 생성
- [ ] ext2_PEPE : Texture 씌우기
- [ ] ext3_PEPE : 생성된 3D 객체를 AR에 띄워보기
- [ ] ext4_PEPE : 3D 객체의 저장 형식 알아보기 (SCNShape, .usdz, ...)

# ⚙️ ETC
- https://stackoverflow.com/questions/53317392/how-to-create-a-scnnode-from-a-usdz
